### ISSUE TITLE
Plotting neuralnet for custom architecture 

### ISSUE THREAD

**Issue by abhigoku10** [HarisIqbal88/PlotNeuralNet#71]
@HarisIqbal88 @Brandon-HY-Lin @pedrodiamel @StevenShi-23  thanks for open sourcing the wonderfull work appreciate the sharing and efffort , i have few queries 
1. Can you use plotneural net for any architectures which is defined in keras, tensorflow or pytorch 
2.If so what is the procedure or steps involved to plot the available architecture 
3.if there any option where current source code takes in the model weights and obtain the plot of any frame work 
4.from the plot neural net can we get more details of the feature maps and it working 

thanks in advance

**Comment by StevenShi-23** [comment]
Hi,

Q1: Yes
Q2: You may refer to [python example](https://github.com/HarisIqbal88/PlotNeuralNet#python-usage) for usage. Basically you need to declare the network arch first and then generate the plot. You may also wish to look into example usages. 
Q3. No, to the best of my knowledge. 
Q4. No, this is just a plotting tool.

**Comment by HarisIqbal88** [comment]
@1.@3@4 This tool was designed to create network diagrams for documents or presentations etc, which requires human supervision for creating clear and understandable images. Hence, you can make diagrams of any sort of network in this, even extend some part to include more shapes. However, it is not possible to automate from model weights or analyze a network at the moment. 
@2. I would also add that try to look at latex examples as well if you are comfortable with latex because you will get full functionality in latex and extending is also easy in that. I personally think that latex interface is easier than python one
